### ISSUE TITLE
FormatDax() doesn't work from command line

### ISSUE THREAD

**Issue by smileydts** [TabularEditor/TabularEditor#975]
**Describe the bug**
`FormatDax()` method doesn't work when calling a script from the command line.

**To Reproduce**
1. Save the following 1 line script: `Model.AllMeasures.FormatDax();`
2. Run the following in the command line:
```
        "start /wait TabularEditor.exe "[.pbit file path]" -S "[script]"
```

**Expected behavior**
All measures get formatted.

**Observed behavior**
Output:

> Tabular Editor 2.16.5 (build 2.16.8004.19200)
> --------------------------------
> Loading model...
> Loaded script: C:\\Users\\Dustin.Steinhauer\\ras-sal\\pbi\\spd\\scripts\\cs\\format_measures.cs
> Executing script 0...
> Using System Proxy without credentials
> Script execution error: Object reference not set to an instance of an object.

Measures don't get formatted.

**Application specifics**
 - Tabular Editor 2.X version: 2.16.5

**Additional context**
Confirmed that the method works as expected in the TE Advanced Scripting window.

**Comment by otykier** [comment]
Fixed in [2.16.6](https://github.com/TabularEditor/TabularEditor/releases/tag/2.16.6). Thanks for reporting!

**Comment by smileydts** [comment]
Thank you for looking into this; however, it doesn't appear to me that the error is completely fixed.  The script no longer errors out, but the measures still don't get formatted.  Here's the output:

> Tabular Editor 2.16.6 (build 2.16.8128.358)
--------------------------------
Loading model...
Loaded script: C:\Users\Dustin.Steinhauer\ras-sal\pbi\scripts\cs\format_measures.cs
Executing script 0...
Using System Proxy without credentials
Using System Proxy without credentials

**Comment by otykier** [comment]
Remember to specify `-D` at the end of the command to indicate that Tabular Editor should save the updated metadata back to the source file after executing the scripts.

**Comment by smileydts** [comment]
Ah yes that worked.  Thanks for the help (and very quick reply).
